### ISSUE TITLE
NoSuchMethodError for android 6

### ISSUE THREAD

**Issue by Nekromancer** [OpenHFT/Zero-Allocation-Hashing#33]
I cannot run xxHash on devices running android 6. Stacktrace:
```
java.lang.NoSuchMethodError: No virtual method getByte(Ljava/lang/Object;J)B in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
        at net.openhft.hashing.UnsafeAccess.getByte(UnsafeAccess.java:87)
        at net.openhft.hashing.UnsafeAccess.getUnsignedByte(UnsafeAccess.java:82)
        at net.openhft.hashing.XxHash.fetch8(XxHash.java:51)
        at net.openhft.hashing.XxHash.xxHash64(XxHash.java:150)
        at net.openhft.hashing.XxHash$AsLongHashFunction.hash(XxHash.java:272)
        at net.openhft.hashing.LongHashFunction.unsafeHash(LongHashFunction.java:453)
        at net.openhft.hashing.LongHashFunction.hashBytes(LongHashFunction.java:494)
```

**Comment by gzm55** [comment]
`Unsafe.getByte()` comes from android 7 (api level 24). so maybe we can use `getInt(ofs - 3) & 0xFF` as a work around.

**Comment by gzm55** [comment]
#35 should fix this issue.

**Comment by Nekromancer** [comment]
Great! When could this be merged into master? Or maybe you could provide me some snapshot on maven so i could test this?

**Comment by gzm55** [comment]
about merging, @leventov do u have time to review #35?
about snapshot, @Nekromancer just clone my fork, and `mvn install` on your machine.

**Comment by dpisklov** [comment]
@gzm55 PR merged, thanks

**Comment by Nekromancer** [comment]
Works great. Is there release coming?

**Comment by dpisklov** [comment]
@Nekromancer @gzm55 zero-allocation-hashing-0.11 is released

**Comment by Nekromancer** [comment]
Great! Will it get released on sonatype too?

**Comment by dpisklov** [comment]
It is there, it just will take time to propagate through - should be available in a few hours, as usual with sonatype...

**Comment by Nekromancer** [comment]
Ok, thanks
