### ISSUE TITLE
net.openhft.hashing.UtilTest#testStringHash fails on Zing

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Zero-Allocation-Hashing#75]

**Comment by gzm55** [comment]
could you plz post the error log? i cannot view the  log the failed github action job.

**Comment by JerryShea** [comment]
```
java.lang.AssertionError: expected not same
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.failSame(Assert.java:820)
  at org.junit.Assert.assertNotSame(Assert.java:799)
  at org.junit.Assert.assertNotSame(Assert.java:812)
  at net.openhft.hashing.UtilTest.testStringHash(UtilTest.java:13)
```

**Comment by JerryShea** [comment]
Fixed by https://github.com/OpenHFT/Zero-Allocation-Hashing/pull/76
